### ISSUE TITLE
possible issue with v23?

### ISSUE THREAD

**Issue by choseh** [OpenVPN/openvpn3-indicator#22] opened 2024-10-24 10:18 UTC
Hi again,

looks like there are issues with v23 from the official openvpn repo.

```
openvpn3-indicator -d
INFO:root:Startup
DEBUG:root:Running with manager version 23
DEBUG:root:Created Indicator 85648c79-407e-408c-af50-615e8835d1e9
INFO:root:Activate
DEBUG:root:Schedule
DEBUG:root:Traceback (most recent call last):
  File "/usr/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 240, in refresh_sessions
    session.StatusChangeCallback(lambda major, minor, message: self.on_session_event(session_id, major, minor, message))
  File "/usr/lib/python3/dist-packages/openvpn3/SessionManager.py", line 352, in StatusChangeCallback
    self.__set_log_forward()
  File "/usr/lib/python3/dist-packages/openvpn3/SessionManager.py", line 462, in __set_log_forward
    self.__session_intf.LogForward(True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.gtk.GDBus.UnmappedGError.Quark._net_2eopenvpn_2egdbuspp_2erequest.Code36: GDBus.Error:net.openvpn.gdbuspp.request: Failed to retrieve UID for bus name ':1.118': Could not get UID of name ':1.118': no such name

WARNING:root:Session list refresh failed
DEBUG:root:Repairing Indicators

(openvpn3-indicator:35480): libayatana-appindicator-WARNING **: 12:16:59.743: Unable to get the session bus: The given address is empty

(openvpn3-indicator:35480): LIBDBUSMENU-GLIB-WARNING **: 12:16:59.743: Unable to get session bus: The given address is empty
DEBUG:root:Schedule
DEBUG:root:Traceback (most recent call last):
  File "/usr/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 240, in refresh_sessions
    session.StatusChangeCallback(lambda major, minor, message: self.on_session_event(session_id, major, minor, message))
  File "/usr/lib/python3/dist-packages/openvpn3/SessionManager.py", line 352, in StatusChangeCallback
    self.__set_log_forward()
  File "/usr/lib/python3/dist-packages/openvpn3/SessionManager.py", line 462, in __set_log_forward
    self.__session_intf.LogForward(True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.gtk.GDBus.UnmappedGError.Quark._net_2eopenvpn_2egdbuspp_2erequest.Code36: GDBus.Error:net.openvpn.gdbuspp.request: Failed to retrieve UID for bus name ':1.118': Could not get UID of name ':1.118': no such name
```

thanks for checking and let me know if you need additional info

**Comment by dsommers** [comment] 2024-10-24 11:10
That error itself is a new race condition which appeared in OpenVPN 3 Linux v23.  This will hopefully be resolved in the next release.  However, openvpn3-inidicator would benefit from having a better error handling with such errors.

**Comment by choseh** [comment] 2024-12-13 17:02
can confirm that this is no longer an issue with v24

**Comment by dsommers** [comment] 2024-12-13 17:07
Thanks!  This should be resolved by [this change](https://codeberg.org/OpenVPN/openvpn3-linux/commit/6af8edd45e7d071f1482d8b1db6e34b7b16ce021) in the v24 release.  I'm sorry I forgot to update this ticket with the v24 release.

Since this is confirmed to be fixed with v24, I'm closing this ticket now.

**Closed by dsommers** 2024-12-13 17:07 UTC
Labels: bug
